export type PageId = 'home' | 'schedule' | 'travel' | 'rsvp' | 'registry'

export type MaterialIconName =
  | 'airport_shuttle'
  | 'arrow_back'
  | 'arrow_forward'
  | 'auto_awesome'
  | 'bakery_dining'
  | 'calendar_today'
  | 'celebration'
  | 'church'
  | 'close'
  | 'directions_car'
  | 'expand_more'
  | 'favorite'
  | 'flight'
  | 'home'
  | 'hotel'
  | 'local_bar'
  | 'location_on'
  | 'map'
  | 'menu'
  | 'music_note'
  | 'redeem'
  | 'restaurant'
  | 'schedule'
  | 'star'
  | 'tips_and_updates'
